<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Manual Decision</name>
  <uuid>ccbdd442-8461-41d5-a33c-fc6213cbe5c6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    'the validate time window' is manual
    or 'the validate type of goods' is manual
then
    set decision to manual ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
