<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>e03ea52e-5958-4ec5-9729-a10229f46435</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to approved ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
