<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default scoreboard</name>
  <uuid>11b03ab8-d43e-4f1b-a94b-c9974a9201f2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Scoreboard where
        the Confidence is 0 , 
        High risk is true ,
        the Segment is "Unknown" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
