<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>get machine learning output</name>
  <uuid>7c3a0f76-56e8-4852-961c-08f100454300</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the predicted clientdefaultedpayment is "TRUE"
then
set decision to a new Scoreboard where 
    High risk is true , 
    the Confidence is the confidence ,
    the Segment is "Unknown" ;
else 
set decision to a new Scoreboard where 
    High risk is false , 
    the Confidence is the confidence ,
    the Segment is "Unknown" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
