<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>build document list with general validation documents</name>
  <uuid>bff2c46f-d9db-4eb2-b59e-7ee9e1767b05</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[then
	add a new Documentation Response where
		the required documents are 'General validations' to decision ;
  
    
    ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
