<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Consolidate Result</name>
  <uuid>3a033d81-5f61-4d5f-abe5-a21d6cdc40fe</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[then
    for each KYC Document Domain in 'Country and rating validations' : 
	- add this KYC Document Domain to the required documents of decision ;
    for each KYC Document Domain in 'General validations' : 
	- add this KYC Document Domain to the required documents of decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
