<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Consolidate Result-With-General-Validations-only</name>
  <uuid>9701d6c7-3fd4-4427-839a-91cb1b6706e2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 
 'Country and rating validations' are undefined 
then
    for each KYC Document Domain in 'General validations' : 
	- add this KYC Document Domain to the required documents lists of decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
