<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Include documents for country and rating validations</name>
  <uuid>91e30b62-df50-4990-9be9-e435459fead3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add a new Documentation Response where
		the required documents are 'Country and rating validations' to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
