<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>include risk from policy validation</name>
  <uuid>17ef67d6-2a28-4954-8ec4-0ab90aaa6173</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Policy validation risk score' is more than 0
then
	set decision to a new Response data where
		the interestRate is the interestRate of decision , 
		isHighRisk is decision is isHighRisk , 
		the riskScore is the riskScore of decision + 'Policy validation risk score', 
		the riskAssesmentMessage is the riskAssesmentMessage of decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
