<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>1999787f-77bd-4a11-b5fc-93a611669280</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Response data where
		the interestRate is 0.05 , 
		isHighRisk is false , 
		the riskScore is 100 , 
		the riskAssesmentMessage is "Default risk assessment, no high risk identified" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
