<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>get machine learning output</name>
  <uuid>c12548e7-9713-4216-9b4d-d87e91f8e234</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
set percent to the maximum score of 'ML model invocation';

if the predictions of 'ML model invocation' is 1
then
set decision to a new Scoreboard where 
    High risk is true , 
	the Confidence is percent,
    the Segment is "Unknown";
else 
set decision to a new Scoreboard where 
    High risk is false , 
	the Confidence is percent,
    the Segment is "Unknown";

]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
