<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>reduce list</name>
  <uuid>ed1fa036-1763-452a-8733-a2dc2664ff43</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each Service called item , in 'Services list'  
if
    the number of elements in decision is less than 'Services count'
then
    add item to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
