<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>0fd50065-5226-41ab-8c8a-be90238ee69a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Sorry, we don't have enough information to privide a result" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
