<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>aed643c5-f234-4fdf-b95b-fe3e11aa513f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
