<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>telecom default</name>
  <uuid>a8ddbb2b-19ee-4e90-8afa-7eaea0faf740</uuid>
  <documentation><![CDATA[Defines the list of available services for the industry Telecom.]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the Industry of Services is Telecom 
then
	add Telecom: Business Devices to decision ;
    add Telecom: Communication Equipment to decision ; 
    add Telecom: Fibre Internet to decision ;
    add Telecom: Tie-line Solution to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
