<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>set client input</name>
  <uuid>1ba88ec4-da8f-42a8-83c8-c75484cf0b87</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
		the clientannualrevenue is the Annual Revenue of 'Client information' , 
		the clientemployeenumber is the Number of Employees of 'Client information' , 
		the clientexistenceduration is the Company Age of 'Client information' , 
		the clientindustry is 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
