<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>consolidate list of documents required</name>
  <uuid>99b6d843-3ade-492d-ae21-96a72975180b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add a new Documentation Response where
		the requiredDocuments are 'General validations' to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
