<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>All FALSE</name>
  <uuid>8e43a35e-ae19-4e1d-a626-d35559e7341a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
	set 'All FALSE' to Prediction 
		where the predicted clientdefaultedpayment of each ML model output is "FALSE" ;
	set 'number of predictions' to the number of elements in Prediction ;
if
	'number of predictions' is more than 0 
then
	set decision to a new ML model output where
		the confidence is the sum of the confidences of 'All FALSE' / 'number of predictions' , 
		the predicted clientdefaultedpayment is "FALSE" , 
		the weight is the sum of the weights of 'All FALSE' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
