<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>add service</name>
  <uuid>8e50c00b-43f6-411a-885d-8befb041ff5b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Additional services count' is 1
then
	add the element  to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
