<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>filter requested</name>
  <uuid>1a776532-4dd6-4c14-ba33-34140d23c0d2</uuid>
  <documentation><![CDATA[This is the final rule of the sequence. It defines the additional services.]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[for each Service in the Services requested :
   - remove this Service from decision , ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
