<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>healthcare default</name>
  <uuid>bdc1f34d-f26c-4c82-9d32-67c8a931b280</uuid>
  <documentation><![CDATA[Defines the list of available services for the industry Healthcare.]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the Industry of Services is Healthcare 
then
	add Healthcare: Employee Benefits Plan to decision ;
    add Healthcare: Mental Health Care to decision ;
	add Healthcare: On-site Medical Testing to decision ;
    add Healthcare: Virtual Medical Assistance to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
