<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>set extended services</name>
  <uuid>9338486d-033e-4dba-b109-fc52ccf55dbc</uuid>
  <documentation><![CDATA[Builds the list of services and fees.]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Service Information where
		the Extended services are 'Additional services' , 
		the Services Fee is Fee ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
