<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Banking license validation for Central Bank</name>
  <uuid>a6a8e658-2c77-42f2-893f-6021fc3c86b2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Primary business purpose' is CENTRAL BANK 
then
    add Banking License to decision ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
