<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Insurer</name>
  <uuid>caf287ce-4f8f-45ec-9d27-c1ae5ad9a861</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Primary business purpose' is INSURER 
then
    add Foreign Bank Certificate to decision ;
    add Formation Certificate to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
