<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>59f93459-6b75-4064-9563-7cfd10a56d08</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to approved ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
