<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>define request type</name>
  <uuid>681eac18-714b-4eed-8ea6-8b63a43a0b5d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
set 'one intent' to an Intent in decision ;
then
set the request type of 'one intent' to AMT ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
