<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>15be9b4b-f342-4e09-b4cf-3f96c8444bf0</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to an empty list of Intents ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
