<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>aec01367-22b6-4acb-8d1a-28ed4c7e0fe8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'Identify Illness' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
