<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Undetermined diagnosis</name>
  <uuid>927f9ec2-d5ec-4ad1-9e41-7249be043db6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the disease of 'Identify Illness' is not one of { ALLERGIES, COLD, CORONAVIRUS , CORONAVIRUS , FLU , HEALTHY  } 
then
    set decision to a new Diagnosis where
        the disease is UNDETERMINED, 
        the recommendations are { "Based on your symptoms, we are unable to determine a definite diagnosis." } ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
