<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>c493aa11-035f-4cd2-a280-a16aa199626f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set 'the intents lists' to an empty list of Intents ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
