<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>98f8cfe2-a3aa-4f79-9351-a6406d2f731e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to an empty list of Intents ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
