<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Banking license required for central bank</name>
  <uuid>c233590a-0afc-4858-8349-2959d9fd254e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Primary business purpose' is CENTRAL BANK 
then
	add Banking License to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
