<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Healthy Patient</name>
  <uuid>012495c0-cb54-4984-bccd-ff0f305e0d74</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    there are 0 Symptoms in Symptom 
then
    set decision to a new Diagnosis where
        the disease is HEALTHY ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
